### ISSUE TITLE
Brew Cask?

### ISSUE THREAD

**Issue by terraboss** [haokaiyang/Mac-QuickLook#4]
> Error: Cask '+' is unavailable: No Cask with this name exists. Did you mean one of these?
> ...

What is the issue? Homebrew runs smoothly and is up-2-date under macOS Catalina.

**Comment by adamwinn** [comment]
It mains you run `brew cask install` and then the package name.  ie.  `brew cask install AsciiDocQuickLook`

**Comment by builder555** [comment]
```
brew install --cask BetterZipQL
Error: Cask 'betterzipql' is unavailable: No Cask with this name exists.
```
Is there more to the command?
